version: '3.0'

services:
  backend:
    build:
      context: ./back_docker
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://ubuntu@i10d207.p.ssafy.io/yourdatabase
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      MYSQL_HOST: db
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./front_docker
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: development
    depends_on:
      - backend

  db:
    image: mysql:8.3.0
    environment:
      MYSQL_DATABASE: jpapractice
      MYSQL_USER: root
      MYSQL_PASSWORD: 0000
      MYSQL_ROOT_PASSWORD: 0000
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data

volumes:
  db-data:
  # redis-data:
