version: '3.0'

services:
  backend:
    build:
      context: ./back_docker
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./front_docker
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - .env
    depends_on:
      - backend

  db:
    image: mysql:8.3.0
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data: