# 사용할 Java 버전에 맞는 기본 이미지를 선택합니다.
FROM openjdk:17-jdk-alpine

# 애플리케이션 파일이 위치할 디렉토리를 생성합니다.
WORKDIR /app

# 호스트 머신에서 빌드된 JAR 파일을 Docker 이미지로 복사합니다.
# JAR 파일 이름이 정확히 일치하는지 확인해야 합니다.
COPY ./build/libs/*SNAPSHOT.jar app.jar

# Spring Boot 애플리케이션은 내장된 톰캣을 사용하여 8080 포트에서 실행됩니다.
EXPOSE 8080

# 애플리케이션 실행
ENTRYPOINT ["java", "-jar", "app.jar"]
